### PR TITLE
Update sbf.h

### PR DESCRIPTION
**Pull request by SeptentrioGNSS**
only overwrite Stream1 in the autoconfig of the Septentrio Receiver, al other streams are untouched

### CODE REVIEW

**Review by bkueng — APPROVED** [review]

**Comment by SeptentrioGNSS** [comment]
@bkueng maybe a stupid question but this is now merged into the main, with the next official release of PX4, will it be included? As there is currently v1.14 released but anything from this point foreward like 1.14.x or 1.15 wil this include this merge?

**Comment by bkueng** [comment]
It will be included in the next major/minor release, but not in point releases like 1.14.x.

**Comment by SeptentrioGNSS** [comment]
What is the procedure to get this merged for the next point release? Is this a direct ask to certain developers?

**Comment by bkueng** [comment]
I quickly did it as it's a small change, but we typically only backport important bug fixes.
https://github.com/PX4/PX4-Autopilot/pull/22759

**Comment by SeptentrioGNSS** [comment]
Ok thank you for this. For the future what is the normal process of getting thing like this and bigger chunks of code included in the next possible release? Is it to create a PR to the release 1.14 branch instead of the main?

**Comment by bkueng** [comment]
> Is it to create a PR to the release 1.14 branch instead of the main?

Yes exactly

**Pull request merged**
