### PR TITLE
sbf: fix subsequent init in QGC

### PR DESCRIPTION
**Pull request by julianoes**
It needed a bit of trial and error to figure out why subsequent configurations in QGC would fail. I eventually settled on the current changes which basically:
- always set up input mode
- always disable all SBF messages to then enable them again
- remove all manual decoder inits and flushes

### CODE REVIEW

**Comment by julianoes** [comment]
@SeptentrioGNSS could you double check this makes sense please? Thanks!

**Comment by julianoes** [comment]
Tested with QGC over USB and PX4 over serial.

**Comment by SeptentrioGNSS** [comment]
> @SeptentrioGNSS could you double check this makes sense please? Thanks!

What should this fix? Not up to speed with the initial problem. Gives me a better perspective to check this.

**Comment by julianoes** [comment]
I don't know really. What I do know is that it didn't work and kept going in a loop, and once I consolidated the logic a bit and removed the reads in-between the operations it started working. It was a bit of trial and error and the code paths for "normal" vs. "RTCM" were strangely different and intertwined making it hard to see what is going on.

**Comment by julianoes** [comment]
Bump, if there are no objections I'm tempted to get this in soon.

**Pull request merged**
